name: "Release [tag]"
on:
  push:
    tags:
      - v*

jobs:
  release:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and deploy image to ghcr.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
            GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.actor }}
            GIT_SHA: ${{ github.sha}}
            GIT_REF: ${{ github.ref}}
            IMAGE: ${{ github.repository }}
        run: |
            ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
            echo "GITHUB_REF=${GIT_REF}, GITHUB_SHA=${GIT_SHA}, GIT_BRANCH=${ref}"
            echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin
            docker buildx build --push \
                --tag ghcr.io/${IMAGE}:${ref} --tag ${IMAGE}:latest .
      -
        name: Create github release
        uses: ncipollo/release-action@v1
        with:
            generateReleaseNotes: true
